# Tarea M3 T01

## Ejercicio 1

In [109]:
from sklearn.datasets import load_iris
import numpy as np

data = load_iris().data
target = load_iris().target

In [110]:
print("Los primeros 10 registros de data son:", '\n',data[0:10,0:])

Los primeros 10 registros de data son: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [111]:
print("Los primeros 10 registros de target son:",target[0:10])

Los primeros 10 registros de target son: [0 0 0 0 0 0 0 0 0 0]


## Ejercicio 2

In [112]:
targetR=target.reshape(150,1)
data_target = np.concatenate((data,targetR), axis=1)
print ("Los primeros 5 registros del array concatenado son:",'\n',data_target [0:5,0:])

Los primeros 5 registros del array concatenado son: 
 [[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


## Ejercicio 3

In [113]:
print("La media de la lóngitud del sépalo es", np.around(np.mean(data_target[:,0:1]),2), "cm")
print("La media de la longitud de los pétalos es", np.around(np.mean(data_target[:,2:3]),2), "cm")
print("La desviación estándar de la lóngitud del sépalo es", np.around(np.std(data_target[:,0:1]),2), "cm")
print("La desviación estándar de la lóngitud de los pétalos es", np.around(np.std(data_target[:,2:3]),2), "cm")

La media de la lóngitud del sépalo es 5.84 cm
La media de la longitud de los pétalos es 3.76 cm
La desviación estándar de la lóngitud del sépalo es 0.83 cm
La desviación estándar de la lóngitud de los pétalos es 1.76 cm


## Ejercicio 4

In [114]:
from numpy import random

In [115]:
print("La muestra aleatoria de 20 registros es:",'\n',data_target[random.randint(len(data_target), size=20),:])

La muestra aleatoria de 20 registros es: 
 [[6.7 3.3 5.7 2.1 2. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.9 3.  4.2 1.5 1. ]
 [5.7 3.8 1.7 0.3 0. ]
 [6.5 3.  5.5 1.8 2. ]
 [5.1 2.5 3.  1.1 1. ]
 [5.8 4.  1.2 0.2 0. ]
 [6.1 3.  4.6 1.4 1. ]
 [4.6 3.6 1.  0.2 0. ]
 [4.9 2.5 4.5 1.7 2. ]
 [4.9 2.5 4.5 1.7 2. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [6.8 3.2 5.9 2.3 2. ]
 [5.8 2.6 4.  1.2 1. ]
 [4.9 3.6 1.4 0.1 0. ]
 [5.5 2.3 4.  1.3 1. ]
 [6.4 2.8 5.6 2.2 2. ]
 [6.3 2.5 4.9 1.5 1. ]]


## Ejercicio 5

## a) 

In [116]:
i = [0,1,2,3] 
Setosa_M=np.round(np.mean([fila [i] for fila in data_target[np.where(data_target[:,-1]==0.)]],0),2)
Versicolor_M=np.round(np.mean([fila [i] for fila in data_target[np.where(data_target[:,-1]==1.)]],0),2)
Virginica_M=np.round(np.mean([fila [i] for fila in data_target[np.where(data_target[:,-1]==2.)]],0),2)
print ("La matriz de medias de cada característica por especie es:", '\n', np.matrix([Setosa_M, Versicolor_M, Virginica_M]))

La matriz de medias de cada característica por especie es: 
 [[5.01 3.43 1.46 0.25]
 [5.94 2.77 4.26 1.33]
 [6.59 2.97 5.55 2.03]]


In [117]:
i = [0,1,2,3] 
SetosaS=np.round(np.std([fila [i] for fila in data_target[np.where(data_target[:,-1]==0.)]],0),3)
VersicolorS=np.round(np.std([fila [i] for fila in data_target[np.where(data_target[:,-1]==1.)]],0),3)
VirginicaS=np.round(np.std([fila [i] for fila in data_target[np.where(data_target[:,-1]==2.)]],0),3)
print ("La matriz de desviaciones estándar de cada característica por especie es:", '\n', 
       np.matrix([SetosaS, VersicolorS, VirginicaS]))

La matriz de desviaciones estándar de cada característica por especie es: 
 [[0.349 0.375 0.172 0.104]
 [0.511 0.311 0.465 0.196]
 [0.629 0.319 0.546 0.272]]


## Ejercicio 6

## a)

In [118]:
Especies, Conteo = np.unique(data_target[:,-1], return_counts=True)
Matriz_conteo = np.column_stack((Especies,Conteo))
print (Matriz_conteo,'\n',"Se han tomado cincuenta muestras por cada especie")

[[ 0. 50.]
 [ 1. 50.]
 [ 2. 50.]] 
 Se han tomado cincuenta muestras por cada especie


## b) 

In [119]:
Arr_medias = np.array((Setosa_M, Versicolor_M, Virginica_M))
print("La especie",load_iris().target_names[np.argmax(Arr_medias[:,0:1])],"con",max(max(i) for i in Arr_medias[:,0:1]),
      "cm es la que tiene el valor máximo promedio en longitud de sépalo")

La especie virginica con 6.59 cm es la que tiene el valor máximo promedio en longitud de sépalo


## Ejercicio 7

## a)

In [120]:
print ("La matriz de correlación de los datos es:",'\n','\n',np.corrcoef(data))

La matriz de correlación de los datos es: 
 
 [[1.         0.99599866 0.99997391 ... 0.65347343 0.6339168  0.63315839]
 [0.99599866 1.         0.99660709 ... 0.70898277 0.68625679 0.68483481]
 [0.99997391 0.99660709 1.         ... 0.65755616 0.63763128 0.6368058 ]
 ...
 [0.65347343 0.70898277 0.65755616 ... 1.         0.99570813 0.99446012]
 [0.6339168  0.68625679 0.63763128 ... 0.99570813 1.         0.99991588]
 [0.63315839 0.68483481 0.6368058  ... 0.99446012 0.99991588 1.        ]]


## b)

In [121]:
print("Los valores mayores a la media de la lóngitud de los pétalos son:","\n",data[np.where(data>np.mean(data[:,2]))])


Los valores mayores a la media de la lóngitud de los pétalos son: 
 [5.1 4.9 4.7 4.6 5.  5.4 3.9 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 4.  5.7
 4.4 5.4 3.9 5.1 5.7 3.8 5.1 3.8 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7
 4.8 5.4 5.2 4.1 5.5 4.2 4.9 5.  5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 3.8
 4.8 5.1 3.8 4.6 5.3 5.  7.  4.7 6.4 4.5 6.9 4.9 5.5 4.  6.5 4.6 5.7 4.5
 6.3 4.7 4.9 6.6 4.6 5.2 3.9 5.  5.9 4.2 6.  4.  6.1 4.7 5.6 6.7 4.4 5.6
 4.5 5.8 4.1 6.2 4.5 5.6 3.9 5.9 4.8 6.1 4.  6.3 4.9 6.1 4.7 6.4 4.3 6.6
 4.4 6.8 4.8 6.7 5.  6.  4.5 5.7 5.5 3.8 5.5 5.8 3.9 6.  5.1 5.4 4.5 6.
 4.5 6.7 4.7 6.3 4.4 5.6 4.1 5.5 4.  5.5 4.4 6.1 4.6 5.8 4.  5.  5.6 4.2
 5.7 4.2 5.7 4.2 6.2 4.3 5.1 5.7 4.1 6.3 6.  5.8 5.1 7.1 5.9 6.3 5.6 6.5
 5.8 7.6 6.6 4.9 4.5 7.3 6.3 6.7 5.8 7.2 6.1 6.5 5.1 6.4 5.3 6.8 5.5 5.7
 5.  5.8 5.1 6.4 5.3 6.5 5.5 7.7 3.8 6.7 7.7 6.9 6.  5.  6.9 5.7 5.6 4.9
 7.7 6.7 6.3 4.9 6.7 5.7 7.2 6.  6.2 4.8 6.1 4.9 6.4 5.6 7.2 5.8 7.4 6.1
 7.9 3.8 6.4 6.4 5.6 6.3 5.1 6.1 5.6 7.7 6.1 6.3 5.6 6.4 

## c)

In [122]:
print("La muestra con los pétalos más grandes es:","\n",data_target[np.argmax(data_target[:,2])])

La muestra con los pétalos más grandes es: 
 [7.7 2.6 6.9 2.3 2. ]


## Ejercicio 8

In [123]:
print("La especie", load_iris().target_names[np.argmax(Arr_medias[:,0]-Arr_medias[:,2])], "con"
      , max(Arr_medias[:,0]-Arr_medias[:,2]),"cm es la que tiene una mayor diferencia en la longitud media" 
      " entre sépalos y pétalos")

La especie setosa con 3.55 cm es la que tiene una mayor diferencia en la longitud media entre sépalos y pétalos
